version: '3.8'

services:
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  server:
    build: ./server
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - mongo
      - redis
    volumes:
      - ./server:/app/server
      - ./shared:/app/server/shared
      - ./seed:/app/seed
      - /app/node_modules

  client:
    build: ./client
    ports:
      - "5173:5173"
    depends_on:
      - server
    volumes:
      - ./client:/app
      - ./shared:/app/shared
      - /app/node_modules

volumes:
  mongo_data: